/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.models

import java.io.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable as KSerializable

/**
 *
 *
 * @param foodId
 * @param amount
 * @param unitId
 */
@KSerializable
data class FoodItem(
    @SerialName(value = "foodId")
    val foodId: kotlin.Int? = null,
    @SerialName(value = "amount")
    val amount: kotlin.Int? = null,
    @SerialName(value = "unitId")
    val unitId: kotlin.Int? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }
}
