/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.models

import com.fediim.fitmetrics.api.models.FoodItem
import java.io.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable as KSerializable

/**
 *
 *
 * @param name
 * @param description
 * @param mealFoods
 */
@KSerializable
data class Meal(
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    @SerialName(value = "description")
    val description: kotlin.String? = null,
    @SerialName(value = "mealFoods")
    val mealFoods: kotlin.collections.List<FoodItem>? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }
}
