/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.ActivityIntradayTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class ActivityIntradayTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActivityIntradayTimeSeriesApi
        // val apiInstance = ActivityIntradayTimeSeriesApi()

        // to test getActivitiesResourceByDateIntraday
        should("test getActivitiesResourceByDateIntraday") {
            // uncomment below to test getActivitiesResourceByDateIntraday
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today.
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | Number of data points to include. Either 1min or 15min. Optional.
            // apiInstance.getActivitiesResourceByDateIntraday(resourcePath, date, detailLevel)
        }

        // to test getActivitiesResourceByDateRangeIntraday
        should("test getActivitiesResourceByDateRangeIntraday") {
            // uncomment below to test getActivitiesResourceByDateRangeIntraday
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val baseDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today.
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | Number of data points to include. Either 1min or 15min. Optional.
            // apiInstance.getActivitiesResourceByDateRangeIntraday(resourcePath, baseDate, endDate, detailLevel)
        }

        // to test getActivitiesResourceByDateRangeTimeSeriesIntraday
        should("test getActivitiesResourceByDateRangeTimeSeriesIntraday") {
            // uncomment below to test getActivitiesResourceByDateRangeTimeSeriesIntraday
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today.
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | Number of data points to include. Either 1min or 15min.
            // val startTime : kotlin.String = startTime_example // kotlin.String | The start of the period in the format HH:mm.
            // val endTime : kotlin.String = endTime_example // kotlin.String | The end of the period in the format HH:mm.
            // apiInstance.getActivitiesResourceByDateRangeTimeSeriesIntraday(resourcePath, date, endDate, detailLevel, startTime, endTime)
        }

        // to test getActivitiesResourceByDateTimeSeriesIntraday
        should("test getActivitiesResourceByDateTimeSeriesIntraday") {
            // uncomment below to test getActivitiesResourceByDateTimeSeriesIntraday
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today.
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | Number of data points to include. Either 1min or 15min.
            // val startTime : kotlin.String = startTime_example // kotlin.String | The start of the period in the format HH:mm.
            // val endTime : kotlin.String = endTime_example // kotlin.String | The end of the period in the format HH:mm.
            // apiInstance.getActivitiesResourceByDateTimeSeriesIntraday(resourcePath, date, detailLevel, startTime, endTime)
        }
    }
}
