/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.ActiveZoneMinutesIntradayTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class ActiveZoneMinutesIntradayTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActiveZoneMinutesIntradayTimeSeriesApi
        // val apiInstance = ActiveZoneMinutesIntradayTimeSeriesApi()

        // to test getAZMByDateIntraday
        should("test getAZMByDateIntraday") {
            // uncomment below to test getAZMByDateIntraday
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | The detail for which data will be returned. **Supported:** 1min | 5min | 15min
            // apiInstance.getAZMByDateIntraday(date, detailLevel)
        }

        // to test getAZMByDateTimeSeriesIntraday
        should("test getAZMByDateTimeSeriesIntraday") {
            // uncomment below to test getAZMByDateTimeSeriesIntraday
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | The detail for which data will be returned. **Supported:** 1min | 5min | 15min
            // val startTime : kotlin.String = startTime_example // kotlin.String | The start of the period in the format HH:mm.
            // val endTime : kotlin.String = endTime_example // kotlin.String | The end of the period in the format HH:mm.
            // apiInstance.getAZMByDateTimeSeriesIntraday(date, detailLevel, startTime, endTime)
        }

        // to test getAZMByIntervalIntraday
        should("test getAZMByIntervalIntraday") {
            // uncomment below to test getAZMByIntervalIntraday
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | The detail for which data will be returned. **Support:** 1min | 5min | 15min
            // apiInstance.getAZMByIntervalIntraday(startDate, endDate, detailLevel)
        }

        // to test getAZMByIntervalTimeSeriesIntraday
        should("test getAZMByIntervalTimeSeriesIntraday") {
            // uncomment below to test getAZMByIntervalTimeSeriesIntraday
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val detailLevel : kotlin.String = detailLevel_example // kotlin.String | The detail for which data will be returned. **Support:** 1min | 5min | 15min
            // val startTime : kotlin.String = startTime_example // kotlin.String | The start of the period in the format HH:mm.
            // val endTime : kotlin.String = endTime_example // kotlin.String | The end of the period in the format HH:mm.
            // apiInstance.getAZMByIntervalTimeSeriesIntraday(startDate, endDate, detailLevel, startTime, endTime)
        }
    }
}
