/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.ActivityTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class ActivityTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActivityTimeSeriesApi
        // val apiInstance = ActivityTimeSeriesApi()

        // to test getActivitiesResourceByDatePeriod
        should("test getActivitiesResourceByDatePeriod") {
            // uncomment below to test getActivitiesResourceByDatePeriod
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the period specified in the format yyyy-MM-dd or today.
            // val period : kotlin.String = period_example // kotlin.String | The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
            // apiInstance.getActivitiesResourceByDatePeriod(resourcePath, date, period)
        }

        // to test getActivitiesResourceByDateRange
        should("test getActivitiesResourceByDateRange") {
            // uncomment below to test getActivitiesResourceByDateRange
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val baseDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The range start date in the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the range.
            // apiInstance.getActivitiesResourceByDateRange(resourcePath, baseDate, endDate)
        }

        // to test getActivitiesTrackerResourceByDatePeriod
        should("test getActivitiesTrackerResourceByDatePeriod") {
            // uncomment below to test getActivitiesTrackerResourceByDatePeriod
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the period specified in the format yyyy-MM-dd or today.
            // val period : kotlin.String = period_example // kotlin.String | The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
            // apiInstance.getActivitiesTrackerResourceByDatePeriod(resourcePath, date, period)
        }

        // to test getActivitiesTrackerResourceByDateRange
        should("test getActivitiesTrackerResourceByDateRange") {
            // uncomment below to test getActivitiesTrackerResourceByDateRange
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource-path; see options in the Resource Path Options section in the full documentation.
            // val baseDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The range start date in the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the range.
            // apiInstance.getActivitiesTrackerResourceByDateRange(resourcePath, baseDate, endDate)
        }
    }
}
