/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.ActiveZoneMinutesTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class ActiveZoneMinutesTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActiveZoneMinutesTimeSeriesApi
        // val apiInstance = ActiveZoneMinutesTimeSeriesApi()

        // to test getAZMTimeSeriesByDate
        should("test getAZMTimeSeriesByDate") {
            // uncomment below to test getAZMTimeSeriesByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val period : kotlin.String = period_example // kotlin.String | The range for which data will be returned. **Supported:** 1d | 7d | 30d | 1w | 1m | 3m | 6m | 1y
            // apiInstance.getAZMTimeSeriesByDate(date, period)
        }

        // to test getAZMTimeSeriesByInterval
        should("test getAZMTimeSeriesByInterval") {
            // uncomment below to test getAZMTimeSeriesByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-dd or today
            // apiInstance.getAZMTimeSeriesByInterval(startDate, endDate)
        }
    }
}
