/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.BodyTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class BodyTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BodyTimeSeriesApi
        // val apiInstance = BodyTimeSeriesApi()

        // to test getBodyResourceByDatePeriod
        should("test getBodyResourceByDatePeriod") {
            // uncomment below to test getBodyResourceByDatePeriod
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource path, which incudes the bmi, fat, or weight options.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The range start date in the format yyyy-MM-dd or today.
            // val period : kotlin.String = period_example // kotlin.String | The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
            // apiInstance.getBodyResourceByDatePeriod(resourcePath, date, period)
        }

        // to test getBodyResourceByDateRange
        should("test getBodyResourceByDateRange") {
            // uncomment below to test getBodyResourceByDateRange
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resource path, which incudes the bmi, fat, or weight options.
            // val baseDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The range start date in the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the range.
            // apiInstance.getBodyResourceByDateRange(resourcePath, baseDate, endDate)
        }
    }
}
