/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.BreathingRateIntradayApi
import io.kotlintest.specs.ShouldSpec

class BreathingRateIntradayApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BreathingRateIntradayApi
        // val apiInstance = BreathingRateIntradayApi()

        // to test getBreathingRateIntradayByDate
        should("test getBreathingRateIntradayByDate") {
            // uncomment below to test getBreathingRateIntradayByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getBreathingRateIntradayByDate(date)
        }

        // to test getBreathingRateIntradayByInterval
        should("test getBreathingRateIntradayByInterval") {
            // uncomment below to test getBreathingRateIntradayByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getBreathingRateIntradayByInterval(startDate, endDate)
        }
    }
}
