/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.BreathingRateApi
import io.kotlintest.specs.ShouldSpec

class BreathingRateApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BreathingRateApi
        // val apiInstance = BreathingRateApi()

        // to test getBreathingRateSummaryByDate
        should("test getBreathingRateSummaryByDate") {
            // uncomment below to test getBreathingRateSummaryByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getBreathingRateSummaryByDate(date)
        }

        // to test getBreathingRateSummaryByInterval
        should("test getBreathingRateSummaryByInterval") {
            // uncomment below to test getBreathingRateSummaryByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getBreathingRateSummaryByInterval(startDate, endDate)
        }
    }
}
