/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.CardioFitnessScoreVO2MaxApi
import io.kotlintest.specs.ShouldSpec

class CardioFitnessScoreVO2MaxApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CardioFitnessScoreVO2MaxApi
        // val apiInstance = CardioFitnessScoreVO2MaxApi()

        // to test getVo2MaxSummaryByDate
        should("test getVo2MaxSummaryByDate") {
            // uncomment below to test getVo2MaxSummaryByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getVo2MaxSummaryByDate(date)
        }

        // to test getVo2MaxSummaryByInterval
        should("test getVo2MaxSummaryByInterval") {
            // uncomment below to test getVo2MaxSummaryByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getVo2MaxSummaryByInterval(startDate, endDate)
        }
    }
}
