/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.FriendsApi
import io.kotlintest.specs.ShouldSpec

class FriendsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FriendsApi
        // val apiInstance = FriendsApi()

        // to test getFriends
        should("test getFriends") {
            // uncomment below to test getFriends
            // apiInstance.getFriends()
        }

        // to test getFriendsLeaderboard
        should("test getFriendsLeaderboard") {
            // uncomment below to test getFriendsLeaderboard
            // apiInstance.getFriendsLeaderboard()
        }
    }
}
