/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.HeartRateVariabilityIntradayApi
import io.kotlintest.specs.ShouldSpec

class HeartRateVariabilityIntradayApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HeartRateVariabilityIntradayApi
        // val apiInstance = HeartRateVariabilityIntradayApi()

        // to test getHrvIntradayByDate
        should("test getHrvIntradayByDate") {
            // uncomment below to test getHrvIntradayByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getHrvIntradayByDate(date)
        }

        // to test getHrvIntradayByInterval
        should("test getHrvIntradayByInterval") {
            // uncomment below to test getHrvIntradayByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getHrvIntradayByInterval(startDate, endDate)
        }
    }
}
