/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.HeartRateTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class HeartRateTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HeartRateTimeSeriesApi
        // val apiInstance = HeartRateTimeSeriesApi()

        // to test getHeartByDatePeriod
        should("test getHeartByDatePeriod") {
            // uncomment below to test getHeartByDatePeriod
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the period specified in the format yyyy-MM-dd or today.
            // val period : kotlin.String = period_example // kotlin.String | The range of which data will be returned. Options are 1d, 7d, 30d, 1w, and 1m.
            // apiInstance.getHeartByDatePeriod(date, period)
        }

        // to test getHeartByDateRange
        should("test getHeartByDateRange") {
            // uncomment below to test getHeartByDateRange
            // val baseDate : kotlin.String = baseDate_example // kotlin.String | The range start date in  the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the range.
            // apiInstance.getHeartByDateRange(baseDate, endDate)
        }
    }
}
