/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.HeartRateVariabilityApi
import io.kotlintest.specs.ShouldSpec

class HeartRateVariabilityApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HeartRateVariabilityApi
        // val apiInstance = HeartRateVariabilityApi()

        // to test getHrvSummaryDate
        should("test getHrvSummaryDate") {
            // uncomment below to test getHrvSummaryDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getHrvSummaryDate(date)
        }

        // to test getHrvSummaryInterval
        should("test getHrvSummaryInterval") {
            // uncomment below to test getHrvSummaryInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getHrvSummaryInterval(startDate, endDate)
        }
    }
}
