/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.IrregularRhythmNotificationsApi
import io.kotlintest.specs.ShouldSpec

class IrregularRhythmNotificationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IrregularRhythmNotificationsApi
        // val apiInstance = IrregularRhythmNotificationsApi()

        // to test getIrnAlertsList
        should("test getIrnAlertsList") {
            // uncomment below to test getIrnAlertsList
            // val sort : kotlin.String = sort_example // kotlin.String | The sort order of entries by date. Use asc (ascending) when using afterDate. Use desc (descending) when using beforeDate.
            // val offset : kotlin.Int = 56 // kotlin.Int | The offset number of entries.
            // val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of entries returned (maximum;10).
            // val beforeDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-ddTHH:mm:ss. Only yyyy-MM-dd is required. Either beforeDate or afterDate should be specified.
            // val afterDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format yyyy-MM-ddTHH:mm:ss. Only yyyy-MM-dd is required. Either beforeDate or afterDate should be specified.
            // apiInstance.getIrnAlertsList(sort, offset, limit, beforeDate, afterDate)
        }

        // to test getIrnProfile
        should("test getIrnProfile") {
            // uncomment below to test getIrnProfile
            // apiInstance.getIrnProfile()
        }
    }
}
