/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.NutritionTimeSeriesApi
import io.kotlintest.specs.ShouldSpec

class NutritionTimeSeriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NutritionTimeSeriesApi
        // val apiInstance = NutritionTimeSeriesApi()

        // to test getFoodsByDateRange
        should("test getFoodsByDateRange") {
            // uncomment below to test getFoodsByDateRange
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resouce path. See options in the Resouce Path Options section in the full documentation.
            // val baseDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The range start date in the format yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the range.
            // apiInstance.getFoodsByDateRange(resourcePath, baseDate, endDate)
        }

        // to test getFoodsResourceByDatePeriod
        should("test getFoodsResourceByDatePeriod") {
            // uncomment below to test getFoodsResourceByDatePeriod
            // val resourcePath : kotlin.String = resourcePath_example // kotlin.String | The resouce path. See options in the Resouce Path Options section in the full documentation.
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The end date of the period specified in the format yyyy-MM-dd or today.
            // val period : kotlin.String = period_example // kotlin.String | The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 3m, 6m, 1y, or max.
            // apiInstance.getFoodsResourceByDatePeriod(resourcePath, date, period)
        }
    }
}
