/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.SpO2IntradayApi
import io.kotlintest.specs.ShouldSpec

class SpO2IntradayApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpO2IntradayApi
        // val apiInstance = SpO2IntradayApi()

        // to test getSpO2IntradayByDate
        should("test getSpO2IntradayByDate") {
            // uncomment below to test getSpO2IntradayByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getSpO2IntradayByDate(date)
        }

        // to test getSpO2IntradayByInterval
        should("test getSpO2IntradayByInterval") {
            // uncomment below to test getSpO2IntradayByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getSpO2IntradayByInterval(startDate, endDate)
        }
    }
}
