/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.SpO2Api
import io.kotlintest.specs.ShouldSpec

class SpO2ApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpO2Api
        // val apiInstance = SpO2Api()

        // to test getSpO2SummaryByDate
        should("test getSpO2SummaryByDate") {
            // uncomment below to test getSpO2SummaryByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getSpO2SummaryByDate(date)
        }

        // to test getSpO2SummaryByInterval
        should("test getSpO2SummaryByInterval") {
            // uncomment below to test getSpO2SummaryByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getSpO2SummaryByInterval(startDate, endDate)
        }
    }
}
