/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.TemperatureApi
import io.kotlintest.specs.ShouldSpec

class TemperatureApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TemperatureApi
        // val apiInstance = TemperatureApi()

        // to test getTempCoreSummaryByDate
        should("test getTempCoreSummaryByDate") {
            // uncomment below to test getTempCoreSummaryByDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getTempCoreSummaryByDate(date)
        }

        // to test getTempCoreSummaryByInterval
        should("test getTempCoreSummaryByInterval") {
            // uncomment below to test getTempCoreSummaryByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getTempCoreSummaryByInterval(startDate, endDate)
        }

        // to test getTempSkinSummaryByInterval
        should("test getTempSkinSummaryByInterval") {
            // uncomment below to test getTempSkinSummaryByInterval
            // val startDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // val endDate : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getTempSkinSummaryByInterval(startDate, endDate)
        }

        // to test getTempSkinSummaryDate
        should("test getTempSkinSummaryDate") {
            // uncomment below to test getTempSkinSummaryDate
            // val date : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | The date in the format of yyyy-MM-dd or today.
            // apiInstance.getTempSkinSummaryDate(date)
        }
    }
}
