/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.apis.UserApi
import io.kotlintest.specs.ShouldSpec

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        // val apiInstance = UserApi()

        // to test getBadges
        should("test getBadges") {
            // uncomment below to test getBadges
            // apiInstance.getBadges()
        }

        // to test getProfile
        should("test getProfile") {
            // uncomment below to test getProfile
            // apiInstance.getProfile()
        }
    }
}
