/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine

open class ActivityIntradayTimeSeriesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null
) : ApiClient(
    baseUrl,
    httpClientEngine,
    httpClientConfig
) {
    /**
     * GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json
     * Get Intraday Time Series
     * Returns the Intraday Time Series for a given resource in the format requested.
     * @param resourcePath The resource-path; see options in the Resource Path Options section in the full documentation.
     * @param date The date in the format yyyy-MM-dd or today.
     * @param detailLevel Number of data points to include. Either 1min or 15min. Optional.
     * @return void
     */
    open suspend fun getActivitiesResourceByDateIntraday(
        resourcePath: kotlin.String,
        date: java.time.LocalDate,
        detailLevel: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json".replace(
                    "{" + "resource-path" + "}",
                    "$resourcePath"
                ).replace(
                    "{" + "date" + "}",
                    "$date"
                ).replace("{" + "detail-level" + "}", "$detailLevel"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json
     * Get Activity Intraday Time Series
     * Returns the Activity Intraday Time Series for a given resource in the format requested.
     * @param resourcePath The resource-path; see options in the Resource Path Options section in the full documentation.
     * @param baseDate The date in the format yyyy-MM-dd or today.
     * @param endDate The date in the format yyyy-MM-dd or today.
     * @param detailLevel Number of data points to include. Either 1min or 15min. Optional.
     * @return void
     */
    open suspend fun getActivitiesResourceByDateRangeIntraday(
        resourcePath: kotlin.String,
        baseDate: java.time.LocalDate,
        endDate: java.time.LocalDate,
        detailLevel: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json".replace(
                    "{" + "resource-path" + "}",
                    "$resourcePath"
                ).replace(
                    "{" + "base-date" + "}",
                    "$baseDate"
                ).replace(
                    "{" + "end-date" + "}",
                    "$endDate"
                ).replace("{" + "detail-level" + "}", "$detailLevel"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/{resource-path}/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json
     * Get Activity Intraday Time Series
     * Returns the Intraday Time Series for a given resource in the format requested.
     * @param resourcePath The resource-path; see options in the Resource Path Options section in the full documentation.
     * @param date The date in the format yyyy-MM-dd or today.
     * @param endDate The date in the format yyyy-MM-dd or today.
     * @param detailLevel Number of data points to include. Either 1min or 15min.
     * @param startTime The start of the period in the format HH:mm.
     * @param endTime The end of the period in the format HH:mm.
     * @return void
     */
    open suspend fun getActivitiesResourceByDateRangeTimeSeriesIntraday(
        resourcePath: kotlin.String,
        date: java.time.LocalDate,
        endDate: java.time.LocalDate,
        detailLevel: kotlin.String,
        startTime: kotlin.String,
        endTime: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/{resource-path}/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json".replace(
                    "{" + "resource-path" + "}",
                    "$resourcePath"
                ).replace(
                    "{" + "date" + "}",
                    "$date"
                ).replace(
                    "{" + "end-date" + "}",
                    "$endDate"
                ).replace(
                    "{" + "detail-level" + "}",
                    "$detailLevel"
                ).replace(
                    "{" + "start-time" + "}",
                    "$startTime"
                ).replace("{" + "end-time" + "}", "$endTime"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json
     * Get Intraday Time Series
     * Returns the Intraday Time Series for a given resource in the format requested.
     * @param resourcePath The resource-path; see options in the Resource Path Options section in the full documentation.
     * @param date The date in the format yyyy-MM-dd or today.
     * @param detailLevel Number of data points to include. Either 1min or 15min.
     * @param startTime The start of the period in the format HH:mm.
     * @param endTime The end of the period in the format HH:mm.
     * @return void
     */
    open suspend fun getActivitiesResourceByDateTimeSeriesIntraday(
        resourcePath: kotlin.String,
        date: java.time.LocalDate,
        detailLevel: kotlin.String,
        startTime: kotlin.String,
        endTime: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json".replace(
                    "{" + "resource-path" + "}",
                    "$resourcePath"
                ).replace(
                    "{" + "date" + "}",
                    "$date"
                ).replace(
                    "{" + "detail-level" + "}",
                    "$detailLevel"
                ).replace(
                    "{" + "start-time" + "}",
                    "$startTime"
                ).replace("{" + "end-time" + "}", "$endTime"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }
}
