/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine

open class ActiveZoneMinutesIntradayTimeSeriesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null
) : ApiClient(
    baseUrl,
    httpClientEngine,
    httpClientConfig
) {
    /**
     * GET /1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json
     * Get AZM Intraday by Date
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.
     * @param date The date in the format yyyy-MM-dd or today
     * @param detailLevel The detail for which data will be returned. **Supported:** 1min | 5min | 15min
     * @return void
     */
    open suspend fun getAZMByDateIntraday(
        date: java.time.LocalDate,
        detailLevel: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json".replace(
                    "{" + "date" + "}",
                    "$date"
                ).replace("{" + "detail-level" + "}", "$detailLevel"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json
     * Get AZM Intraday by Date
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.
     * @param date The date in the format yyyy-MM-dd or today
     * @param detailLevel The detail for which data will be returned. **Supported:** 1min | 5min | 15min
     * @param startTime The start of the period in the format HH:mm.
     * @param endTime The end of the period in the format HH:mm.
     * @return void
     */
    open suspend fun getAZMByDateTimeSeriesIntraday(
        date: java.time.LocalDate,
        detailLevel: kotlin.String,
        startTime: kotlin.String,
        endTime: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json".replace(
                    "{" + "date" + "}",
                    "$date"
                ).replace(
                    "{" + "detail-level" + "}",
                    "$detailLevel"
                ).replace(
                    "{" + "start-time" + "}",
                    "$startTime"
                ).replace("{" + "end-time" + "}", "$endTime"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json
     * Get AZM Intraday by Interval
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.
     * @param startDate The date in the format yyyy-MM-dd or today
     * @param endDate The date in the format yyyy-MM-dd or today
     * @param detailLevel The detail for which data will be returned. **Support:** 1min | 5min | 15min
     * @return void
     */
    open suspend fun getAZMByIntervalIntraday(
        startDate: java.time.LocalDate,
        endDate: java.time.LocalDate,
        detailLevel: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json".replace(
                    "{" + "start-date" + "}",
                    "$startDate"
                ).replace(
                    "{" + "end-date" + "}",
                    "$endDate"
                ).replace("{" + "detail-level" + "}", "$detailLevel"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/time/{start-time}/{end-time}.json
     * Get AZM Intraday by Interval
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.
     * @param startDate The date in the format yyyy-MM-dd or today
     * @param endDate The date in the format yyyy-MM-dd or today
     * @param detailLevel The detail for which data will be returned. **Support:** 1min | 5min | 15min
     * @param startTime The start of the period in the format HH:mm.
     * @param endTime The end of the period in the format HH:mm.
     * @return void
     */
    open suspend fun getAZMByIntervalTimeSeriesIntraday(
        startDate: java.time.LocalDate,
        endDate: java.time.LocalDate,
        detailLevel: kotlin.String,
        startTime: kotlin.String,
        endTime: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/time/{start-time}/{end-time}.json".replace(
                    "{" + "start-date" + "}",
                    "$startDate"
                ).replace(
                    "{" + "end-date" + "}",
                    "$endDate"
                ).replace(
                    "{" + "detail-level" + "}",
                    "$detailLevel"
                ).replace(
                    "{" + "start-time" + "}",
                    "$startTime"
                ).replace("{" + "end-time" + "}", "$endTime"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }
}
