/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine

open class ActiveZoneMinutesTimeSeriesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null
) : ApiClient(
    baseUrl,
    httpClientEngine,
    httpClientConfig
) {
    /**
     * GET /1/user/-/activities/active-zone-minutes/date/{date}/{period}.json
     * Get AZM Time Series by Date
     * Returns the daily summary values over a period of time by specifying a date and time period.
     * @param date The date in the format yyyy-MM-dd or today
     * @param period The range for which data will be returned. **Supported:** 1d | 7d | 30d | 1w | 1m | 3m | 6m | 1y
     * @return void
     */
    open suspend fun getAZMTimeSeriesByDate(
        date: java.time.LocalDate,
        period: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/active-zone-minutes/date/{date}/{period}.json".replace(
                    "{" + "date" + "}",
                    "$date"
                ).replace("{" + "period" + "}", "$period"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}.json
     * Get AZM Time Series by Interval
     * Returns the daily summary values over an interval by specifying a date range.
     * @param startDate The date in the format yyyy-MM-dd or today
     * @param endDate The date in the format yyyy-MM-dd or today
     * @return void
     */
    open suspend fun getAZMTimeSeriesByInterval(
        startDate: java.time.LocalDate,
        endDate: java.time.LocalDate
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}.json".replace(
                    "{" + "start-date" + "}",
                    "$startDate"
                ).replace("{" + "end-date" + "}", "$endDate"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }
}
