/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.apis

import com.fediim.fitmetrics.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine

open class BodyTimeSeriesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null
) : ApiClient(
    baseUrl,
    httpClientEngine,
    httpClientConfig
) {
    /**
     * GET /1/user/-/body/{resource-path}/date/{date}/{period}.json
     * Get Body Time Series
     * Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.
     * @param resourcePath The resource path, which incudes the bmi, fat, or weight options.
     * @param date The range start date in the format yyyy-MM-dd or today.
     * @param period The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
     * @return void
     */
    open suspend fun getBodyResourceByDatePeriod(
        resourcePath: kotlin.String,
        date: java.time.LocalDate,
        period: kotlin.String
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/body/{resource-path}/date/{date}/{period}.json".replace(
                    "{" + "resource-path" + "}",
                    "$resourcePath"
                ).replace("{" + "date" + "}", "$date").replace("{" + "period" + "}", "$period"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }

    /**
     * GET /1/user/-/body/{resource-path}/date/{base-date}/{end-date}.json
     * Get Body Time Series
     * Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.
     * @param resourcePath The resource path, which incudes the bmi, fat, or weight options.
     * @param baseDate The range start date in the format yyyy-MM-dd or today.
     * @param endDate The end date of the range.
     * @return void
     */
    open suspend fun getBodyResourceByDateRange(
        resourcePath: kotlin.String,
        baseDate: java.time.LocalDate,
        endDate: java.time.LocalDate
    ): HttpResponse<Unit> {
        val localVariableAuthNames = listOf<String>("oauth2")

        val localVariableBody =
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig =
            RequestConfig<kotlin.Any?>(
                RequestMethod.GET,
                "/1/user/-/body/{resource-path}/date/{base-date}/{end-date}.json".replace(
                    "{" + "resource-path" + "}",
                    "$resourcePath"
                ).replace(
                    "{" + "base-date" + "}",
                    "$baseDate"
                ).replace("{" + "end-date" + "}", "$endDate"),
                query = localVariableQuery,
                headers = localVariableHeaders,
                requiresAuthentication = true
            )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }
}
