/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.models

import com.fediim.fitmetrics.api.models.FoodItem
import io.kotlintest.specs.ShouldSpec

class FoodItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FoodItem
        // val modelInstance = FoodItem()

        // to test the property `foodId`
        should("test foodId") {
            // uncomment below to test the property
            // modelInstance.foodId shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            // modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `unitId`
        should("test unitId") {
            // uncomment below to test the property
            // modelInstance.unitId shouldBe ("TODO")
        }
    }
}
