/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.fediim.fitmetrics.api.models

import com.fediim.fitmetrics.api.models.FoodItem
import com.fediim.fitmetrics.api.models.Meal
import io.kotlintest.specs.ShouldSpec

class MealTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Meal
        // val modelInstance = Meal()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            // modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            // modelInstance.description shouldBe ("TODO")
        }

        // to test the property `mealFoods`
        should("test mealFoods") {
            // uncomment below to test the property
            // modelInstance.mealFoods shouldBe ("TODO")
        }
    }
}
